#!/usr/bin/env python

import rospy
from std_msgs.msg import Int32

rospy.init_node('publisher_topic')
pub = rospy.Publisher('counter', Int32, queue_size=10)

count = 0
while not rospy.is_shutdown():
    pub.publish(count)
    count += 1
    rospy.Rate(5).sleep ()